config/routes.rb
Rails.application.routes.draw do

  resources :registered_applications

  namespace :api, defaults: { format: :json } do
    match 'events', to: 'events#create', via: [:options]
    resources :events, only: [:create]
  end

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  root :to => "welcome#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
# == Schema Information
#
# Table name: registered_applications
#
#  id         :integer          not null, primary key
#  name       :string
#  url        :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy

  validates :user, presence: true
  validates :name, presence: true
  validates :url, presence: true, uniqueness: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  # Skip CSRF protection in development
  skip_before_action :verify_authenticity_token
  before_filter :set_access_control_headers

  def set_access_control_headers
# #1
    headers['Access-Control-Allow-Origin'] = '*'
# #2
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
# #3
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application == nil
      render json: "Unregistered application", status: :unprocessable_entity
      return
    end
    puts "here are the registered_application"
    puts "#{registered_application}"
    @event = registered_application.events.build(event_params)
    if @event.save
      render json: @event, status: :created
    else
      render @event.errors, status: :unprocessable_entity
    end
  end

  private
  def event_params
    puts "here are the params #{params}"
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    registered_applications_path
  end

end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController

  def index
    @registered_applications = current_user.registered_applications.all
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
  end

  def create
    @registered_application = current_user.registered_applications.build(reg_app_params)

    if @registered_application.save
      redirect_to registered_applications_path
    else
      flash[:error] = "Error registering the application. Please try again."
      render :new
    end
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])

    if @registered_application.update_attributes(reg_app_params)
      redirect_to registered_applications_path
    else
      flash[:error] = "Error updating the application. Please try again."
      render :edit
    end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])

    if @registered_application.destroy
      flash[:notice] = "\"#{@registered_application.name}\" was deleted successfully."
      redirect_to registered_applications_path
    else
      flash[:error] = "There was an error deleting the application."
      render :show
    end
  end




  private

  def reg_app_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/api/events_helper.rb
module API::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end
  
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
   <head>
     <title>Blocmetrics</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <%= stylesheet_link_tag    "application", media: "all" %>
     <%= javascript_include_tag "application" %>
     <%= csrf_meta_tags %>
   </head>
   <body>
     <div class="container">
       <ul class="nav nav-tabs">
         <li><%= link_to "Home", root_path %></li>
         <li><%= link_to "About", welcome_about_path %></li>
         <li><%= link_to "Your Applications", registered_applications_path %></li>

         <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>

       </ul>

       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

       <%= yield %>
     </div>

   </body>
 </html>

app/views/registered_applications/_form.html.erb
<div class= "col-md-4">
  <% if current_user %>
    <%= form_for @registered_application do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter Application Name" %>
      </div>
      <div class= "form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control', placeholder: "Enter Application URL"%>
      </div>
      <div class="form-group">
        <%= f.submit "Submit Application", class: 'btn btn-success' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/registered_applications/edit.html.erb
<div class= "row">
  <h3> Edit application details. </h3>
  <%= render partial: 'form', locals: {user: @user, registered_application: @registered_application} %>
</div>

app/views/registered_applications/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<div class="row">
  <h2>Applications you're tracking</h2>
  <div class= "col-md-8">
    <table class="table table-striped table-hover">
      <tbody>
      <thead>
        <tr>
          <th>Application Name</th>
          <th>URL</th>
          <th>Options</th>
        </tr>
      </thead>
        <% @registered_applications.each do |registered_application| %>
        <tr>
          <td><%= link_to registered_application.name, registered_application %></td>
          <td><%= link_to registered_application.url, registered_application.url %></td>
          <td>
            <%= link_to "Edit", edit_registered_application_path(registered_application), class: 'btn btn-success' %>
            <%= link_to "Delete", registered_application_path(registered_application), method: :delete, data: {confirm: "Are you you sure you want to delete this application?"}, class: 'btn btn-danger' %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
      <%= link_to "Track a new application", new_registered_application_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/registered_applications/new.html.erb
<div class= "row">
  <h3> Track another application. </h3>
  <%= render partial: 'form', locals: {user: @user, registered_application: @registered_application} %>
</div>

app/views/registered_applications/show.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<div class="well well-sm">
    <h3><%= @registered_application.name %></h3>
    <h4><%= link_to @registered_application.url, @registered_application.url %></h4>
</div>
<h4> Application Events </h4>
<div class = "row">

  <% @events.each do |event, name| %>
    <%= event %>
    <%= pie_chart @registered_application.events.group(:name).count %>
    <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
    <hr>
  <% end %>
</div><br>

<div class= "row">
  <%= link_to "Registered Applications", registered_applications_path, class: 'btn btn-success' %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Blocmetrics</h1>
  <p>Blocmetrics is an analytics app</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Yes, we are analyzing data about you</h2>
    <p>There's no getting around it, you're right, it is a little bit creepy.</p>
  </div>
  <div class="col-md-4">
    <h2>Are analytics making us more boring?</h2>
    <p>Well, that depends on what you do with the data. If you use it to help make more intelligent decisions, you'll be ok. If you use it to make decisions full stop, that's on you.</p>
  </div>
  <div class="col-md-4">
    <h2>What do you know about me?</h2>
    <p>A lot less than you have willfully volunteered across a range of social media apps, streaming services and search engines.</p>
  </div>
</div>